/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Form: typeof import('@primevue/forms/form')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaSelector: typeof import('./src/components/SchemaSelector.vue')['default']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Select: typeof import('primevue/select')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    Toast: typeof import('primevue/toast')['default']
    Tree: typeof import('primevue/tree')['default']
    TreeNode: typeof import('./src/components/TreeNode.vue')['default']
    TreeSelect: typeof import('primevue/treeselect')['default']
  }
}
